services:
  sqledge:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: mssql-jiginventory
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=Bb42461503
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume:
